### ISSUE TITLE
Make "Garden" field read only to gardeners on plot edit view

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#69] opened 2018-01-10 15:56 UTC
- "Select Garden" isn't pulling in data at all
- Submitting the form appears like it should be working, but then nothing happens and it reverts to previous state

**Comment by alexgleason** [comment] 2018-01-11 20:50
I'm not able to reproduce this bug.

**Comment by marykatefain** [comment] 2018-01-11 21:55
Okay so this is happening because the template is rendering the gardens based on `user.get_gardens`, which pulls all gardens that user may _manage_. The only reason you were not able to reproduce the bug when logged in as Testy McTesterson was because I just so happened to randomly click that user's name when selecting a GM for Spring Gardens. This bug will  appear for every normal user (aka "gardener" who is not a GM) (ex. Super).

I suggest we actually change some of how this is functioning anyways:

1. Gardeners (non-GMs) should be able to see the garden that their plot is assigned to, but not change it. We may not even want gardeners to be edit the plot's name (let's ask @JenniferGold this tomorrow). The only thing I think gardeners should be editing are the crops in the garden - HOWEVER they should still be able to _see_ that information

2. GMs should be able to edit all of the above

So I think we're going to want to refactor a little of how this template is returning those pieces of information.

**Comment by alexgleason** [comment] 2018-01-11 22:08
Oh, right. Only a GM should have the ability to edit a Plot's garden. A gardener just shouldn't see that field at all. Do you agree?

**Comment by marykatefain** [comment] 2018-01-11 22:12
Hmm... It wouldn't hurt to allow the user to see the Garden that the plot is in somewhere - maybe as a title text field? This way they know which plot they are editing if they have plots in multiple gardens

So at the top of the page they may see "Editing Spring Gardens, Plot #6" and then only see the crops field below. 

Along the same lines, but I forgot to mention it earlier - regular gardeners also should not be remove themselves from their plot. However they may want to add additional users (like a spouse) to manage the plot with them - so I think we can keep the Gardeners field, just with the caviat that they should not see the ability to remove themselves.

**Comment by alexgleason** [comment] 2018-01-11 22:13
Well, either everyone or no one should be able to remove themselves from an object.

**Comment by marykatefain** [comment] 2018-01-11 22:17
I think pretty no one should be able to remove themselves from anything. GMs should be able to remove any gardener from any plot (this may actually include removing themselves from a plot if they happen to have one in a garden they manage), and any plot from any garden, but not a themselves from managing their garden.

Gardeners who are not GMs shouldn't be removing anyone from anything, really. I suppose unless they added them there in the first place (like a secondary gardener on the plot).

**Comment by alexgleason** [comment] 2018-01-11 22:18
Okay well that's a separate issue, can you make one (and put it on the milestone if you think it should be done by tomorrow)?

**Comment by marykatefain** [comment] 2018-01-11 22:19
Nah I'm just thinking outloud answers to your questions. I'll make a new issue for milestone 1.0.0.

Only thing I'm worried about on this issue for tomorrow is what you updated the title to.

**Comment by marykatefain** [comment] 2018-01-11 22:20
Actually I will add this on the agenda to talk to Jen about - she may have more insight into who needs permission for what

**Comment by alexgleason** [comment] 2018-01-11 22:46
This is resolved:

```python
    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        garden = self.object.garden
        garden_field = form.fields['garden']
        # Garden options should be all gardens the user can manage
        # plus the current Plot's garden
        user_gardens = self.request.user.get_gardens()
        garden_queryset = user_gardens.union(
            Garden.objects.filter(id=garden.id)
        )
        # Constrain Garden choices
        # We have to do this here because we can access the Request
        garden_field.queryset = garden_queryset
        # Only managers of the plot's garden can change its garden
        if not self.request.user.can_edit_garden(garden):
            garden_field.disabled = True
        return form
```

1. The garden of the current plot is always added to the queryset of the "garden" field, so it will always populate.
2. The garden field is disabled, unless the user can edit the garden that the plot is currently assigned to.
3. When the garden field is enabled, the user can select among gardens they manage.

via 6b0fa51e05b469837879a3a271836035ac53337f

**Closed by alexgleason** 2018-01-11 22:46 UTC
Labels: bug, need client review, refactor

**Comment by JenniferGold** [comment] 2018-01-12 01:18
Well, it depends on how the UI flow works.  A gardener can have a plot in
multiple gardens.  They might want to create orders and/or edit their crops
for each of their plots in one session/login.  So they need to know which
plot in which garden they are working with at any one time.  Does this make
sense?

For example, my friend Otto has a plot in Liberty Lands, Seedy Acres,
Orianna Hill, and La Finquita.  He grows different crops in each.  He
should be able to edit/manage all his plots from his single login username.

**Comment by alexgleason** [comment] 2018-01-12 01:27
> For example, my friend Otto has a plot in Liberty Lands, Seedy Acres, Orianna Hill, and La Finquita. He grows different crops in each. He should be able to edit/manage all his plots from his single login username.

This is how it currently works, so we're good on that.

The question involves two people *on the exact same plot.* For instance, Mark has a plot in Spring Garden except he's really lazy and never updates GardenHub. His wife isn't lazy, so he invites her to co-manage the Plot on GardenHub and now she has her own login with the ability to make orders on the plot.

GardenHub already supports this feature, it's built into the code. The question is, **can Mark's wife delete Mark from his own plot?**

Technically the answer is *probably not*, but I don't think it's a big enough concern that we should spend a lot of time adding these provisions in. If Mark and his wife have that many problems maybe they should reconsider their marriage and it's not really our problem. At worst Mike could talk to the Spring Garden GM who would have the ability to restore Mark to his plot.

**Comment by JenniferGold** [comment] 2018-01-12 01:48
Hahahaha, I totally agree!
