### ISSUE TITLE
Indicate to Pickers which orders they have already picked today

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#85] opened 2018-01-12 00:08 UTC
As of now it seems that there is no indication on the employee's Home/Assignments screen which orders they have already picked today.

Perhaps the box should display a dimmer and check box over it like the crops do when they are clicked to indicate that this plot is good for today? The indicator could reset each day.

Maybe they should also be filtier on the employee's screen so that ones that have been completed today move to the bottom of the page under a section called: "Orders Picked Today:" or something.

Screenshot for reference:
![screenshot from 2018-01-11 19 04 25](https://user-images.githubusercontent.com/17955536/34853586-902aff58-f702-11e7-8ec2-10a02d7fd432.png)

**Comment by marykatefain** [comment] 2018-01-12 00:09
Another idea: maybe that green check mark just appears over (or in place of) the image of the crops they picked.

**Comment by alexgleason** [comment] 2018-01-12 00:55
You sure? Order has [`Order.was_picked_today()`](http://gardenhub.readthedocs.io/en/latest/models.html#gardenhub.models.Order.was_picked_today) and I'm using it on the homescreen.

```
<div class="card{% if order.was_picked_today %} picked{% endif %}">
```

and,

```
{% if order.was_picked_today %}
  <i class="right floated grey check circle icon"></i>
{% else %}
  <i class="right floated green circle icon"></i>
{% endif %}
```

**Comment by alexgleason** [comment] 2018-01-12 00:57
Um after checking I can see it's returning the wrong value when it should return true, but the tests are passing. 🙃 God, I hope this isn't about timezones.

**Comment by marykatefain** [comment] 2018-01-12 00:59
Well here are two screen shots I took immediately after placing a "pick" if it helps... The first one shows the activity feed on the order proving that a pick was registered, and the second shows what the order looked like on the home screen:

![screenshot from 2018-01-11 19 04 41](https://user-images.githubusercontent.com/17955536/34854798-dd9ad612-f709-11e7-9516-21697d7086cd.png)


![screenshot from 2018-01-11 19 04 25](https://user-images.githubusercontent.com/17955536/34854811-f230e3b4-f709-11e7-8023-57d73203eef6.png)

**Comment by marykatefain** [comment] 2018-01-12 01:00
Sounds like we're on the same page re: design, though.

**Comment by alexgleason** [comment] 2018-01-12 01:06
```
>>> from gardenhub.models import Order
>>> o = Order.objects.get(id=5)
>>> o
<Order: 5>
>>> o.was_picked_today()
/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py:1365: RuntimeWarning: DateTimeField Pick.timestamp received a naive datetime (2018-01-12 00:00:00) while time zone support is active.
  RuntimeWarning)
False
```

Just confirmed, it is because of timezones.

![screenshot-2018-1-11 gardenhub 4](https://user-images.githubusercontent.com/3639540/34854904-c337ca7c-f70a-11e7-851f-45f8592191e1.png)

Here's what an order looks like when it's been picked today, compared to the unpicked one below it.

Setting `USE_TZ = False` and then making the pick fixed the error.

I'm closing this because timezones are a separate issue. I'm on the fence about even implementing support for it.

**Closed by alexgleason** 2018-01-12 01:06 UTC
Labels: UI/UX, employees
